### ISSUE TITLE
Dodać sadzonki do Seasons

### ISSUE THREAD

**Issue by marcin212** [Starchasers/ImmersiveFactory-Modpack#1]
- [x] `xlfoodmod:rice_seeds` lato, jesien
- [x] `xlfoodmod:pepper_seeds` wiosna, lato
- [x] `xlfoodmod:corn_seeds` wiosna,lato,jesien
- [x] `xlfoodmod:cucumber_seeds`, wiosna,lato
- [x] `xlfoodmod:lettuce_seeds`, wiosna,lato
- [x] `xlfoodmod:tomato_seeds`,wiosna,lato
- [x] `xlfoodmod:strawberry_seeds` wiosna

**Comment by Kuboczoch** [comment]
- [x] xlfoodmod:rice_seeds jesien
- [x] xlfoodmod:pepper_seeds wiosna, lato
- [x] xlfoodmod:strawberry_seeds wiosna

reszta bez zmian, przynajmniej tak mi sie wydaje
