### ISSUE TITLE
Prąd mi się marnuje

### ISSUE THREAD

**Issue by Acerixx** [Starchasers/ImmersiveFactory-Modpack#18]
Na końcu każdej linii jest piecyk.

![2019-07-16_10 15 43](https://user-images.githubusercontent.com/9009175/61277725-0f593580-a7b3-11e9-98ed-a015e6036899.png)
![2019-07-16_10 15 52](https://user-images.githubusercontent.com/9009175/61277726-0f593580-a7b3-11e9-8314-a10e23674f00.png)

**Comment by marcin212** [comment]
fixed
