### ISSUE TITLE
Only one type of jetpack is available

### ISSUE THREAD

**Issue by KocproZ** [Starchasers/ImmersiveFactory-Modpack#2]
The creative one

**Comment by serekk11** [comment]
W sumie jetpacki zakłócać będą dotychczasowy balans więc w sumie nie wiem czy warto je dodawać. Za chwilę każdy będzie latał i chuj z łodzi koni innych pociągów. Jeśli je dodawać to zmieniamy recepty na takie w chuj pojebane plus zwiększamy zużycie paliwa żeby nie było sensu nimi latać na duże odległości

**Comment by KocproZ** [comment]
Można po prostu tylko 1 tier dodać, wtedy używane byłyby tylko do transportu góra/dół bo np. zbyt szybko się opada żeby budować
