### ISSUE TITLE
Sugestia balansu

### ISSUE THREAD

**Issue by Kuboczoch** [Starchasers/ImmersiveFactory-Modpack#20]
Nie jestem pewien czy tak ma to być, ale zamiast wielkich pól uprawnych albo kopania surowców ludzie stawiają **cloche oraz excavator**, jest to wybitnie niezbalansowane.
Tylko sugeruje aby zwiększyć utrzymanie tych rzeczy, aby nie była to _"nieskończona kopalnia złota"_ za troche pradu. Psuje bardzo balans i ceny na rynku.

**Comment by marcin212** [comment]
Omówione na TS. Zostaje bez zmian
