### ISSUE TITLE
Paliwo, łodzie, immersiv

### ISSUE THREAD

**Issue by serekk11** [Starchasers/ImmersiveFactory-Modpack#9]
Motorówki zużywają absurdalne ilości paliwa. Np kubczoch jak płynie do mnie 2x tankuje
..  jak się da to zmniejszyć zużycie o 75%

**Comment by marcin212** [comment]
Zużycie paliwa jest w mb na tick. Jest wpisane 1 mniej się nie da. Rozmiaru baku nie da się zwiększyć
